/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        DarkStrategySelect: typeof import('./../components/dark/DarkStrategySelect.vue')['default'];
        ElAside: typeof import('element-plus/es')['ElAside'];
        ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer'];
        ElAvatar: typeof import('element-plus/es')['ElAvatar'];
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElCard: typeof import('element-plus/es')['ElCard'];
        ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
        ElContainer: typeof import('element-plus/es')['ElContainer'];
        ElDrawer: typeof import('element-plus/es')['ElDrawer'];
        ElDropdown: typeof import('element-plus/es')['ElDropdown'];
        ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
        ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
        ElFooter: typeof import('element-plus/es')['ElFooter'];
        ElForm: typeof import('element-plus/es')['ElForm'];
        ElFormItem: typeof import('element-plus/es')['ElFormItem'];
        ElHeader: typeof import('element-plus/es')['ElHeader'];
        ElIcon: typeof import('element-plus/es')['ElIcon'];
        ElInput: typeof import('element-plus/es')['ElInput'];
        ElMain: typeof import('element-plus/es')['ElMain'];
        ElMenu: typeof import('element-plus/es')['ElMenu'];
        ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
        ElOption: typeof import('element-plus/es')['ElOption'];
        ElRow: typeof import('element-plus/es')['ElRow'];
        ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
        ElSelect: typeof import('element-plus/es')['ElSelect'];
        ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
        ElSwitch: typeof import('element-plus/es')['ElSwitch'];
        ElTable: typeof import('element-plus/es')['ElTable'];
        ElTableV2: typeof import('element-plus/es')['ElTableV2'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
    }
}
