/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        VanButton: typeof import('vant/es')['Button'];
        VanCell: typeof import('vant/es')['Cell'];
        VanCellGroup: typeof import('vant/es')['CellGroup'];
        VanCol: typeof import('vant/es')['Col'];
        VanConfigProvider: typeof import('vant/es')['ConfigProvider'];
        VanField: typeof import('vant/es')['Field'];
        VanForm: typeof import('vant/es')['Form'];
        VanGrid: typeof import('vant/es')['Grid'];
        VanGridItem: typeof import('vant/es')['GridItem'];
        VanIcon: typeof import('vant/es')['Icon'];
        VanImage: typeof import('vant/es')['Image'];
        VanLoading: typeof import('vant/es')['Loading'];
        VanNavBar: typeof import('vant/es')['NavBar'];
        VanNoticeBar: typeof import('vant/es')['NoticeBar'];
        VanPicker: typeof import('vant/es')['Picker'];
        VanPopup: typeof import('vant/es')['Popup'];
        VanRow: typeof import('vant/es')['Row'];
        VanSearch: typeof import('vant/es')['Search'];
        VanSpace: typeof import('vant/es')['Space'];
        VanSticky: typeof import('vant/es')['Sticky'];
        VanTab: typeof import('vant/es')['Tab'];
        VanTabbar: typeof import('vant/es')['Tabbar'];
        VanTabbarItem: typeof import('vant/es')['TabbarItem'];
        VanTabs: typeof import('vant/es')['Tabs'];
    }
}
