name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Build
        run: |
          npm -v
          pnpm -v
          pnpm install
          pnpm run build:site:git
          pnpm run build:admin:git
          pnpm run build:mobile:git
          pnpm run build:webapp:git
      - name: Copy Assets
        run: |
          root=$(pwd)
          mkdir -p ./dist/
          mv ./apps/site/dist/** ./dist/
          mkdir -p ./dist/webapp
          mv ./apps/webapp/dist/** ./dist/webapp/
          mkdir -p ./dist/admin
          mv ./apps/admin/dist/** ./dist/admin/
          mkdir -p ./dist/mobile
          mv ./apps/mobile/dist/** ./dist/mobile/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: dist
          force: true
